In [8]:
def isSparse(arr,m, n) : 
    c=0
    for i in range(0,m) : 
        for j in range(0,n) : 
            if (array[i][j] == 0) : 
                c =c + 1
    if (c > ((m * n) // 2)):
        print("Yes") 
    else : 
        print("No") 

arr1 = [ [ 0,0,0,1 ], 
          [ 0,1,0,1 ], 
          [ 0,1,0,0],
          [0,0,2,0]] 
arr2 = [ [ 0,20,0,0 ], 
          [ 0,0,15,0 ], 
          [ 0,24,0,0],
          [0,0,0,30]] 

m = 3
n = 3

isSparse(arr1,m,n)
isSparse(arr2,m,n)

Yes
Yes


In [43]:
import numpy as np
def sparse(arr,m,n):
    k=0
    a1=np.zeros(shape=(6,3),dtype=int)
    for i in range(0,m+1) :
        for j in range(0,n+1) :
            if (arr[i][j] > 0) :
                a1[k][0]=i
                a1[k][1]=j
                a1[k][2]=arr[i][j]
        k=k+1
    return(a1)
m=3
n=3
a1=sparse(arr2,m,n)
a2=sparse(arr1,m,n)
print(a1)
print(a2)               

[[ 0  1 20]
 [ 1  2 15]
 [ 2  1 24]
 [ 3  3 30]
 [ 0  0  0]
 [ 0  0  0]]
[[0 3 1]
 [1 3 1]
 [2 1 1]
 [3 2 2]
 [0 0 0]
 [0 0 0]]
