CREATING ADJACENCY MATRIIX

In [17]:
import numpy as np
a=np.array( [[0, 4, 0, 0, 0, 0, 0, 8, 0], 
        [4, 0, 8, 0, 0, 0, 0, 11, 0], 
        [0, 8, 0, 7, 0, 4, 0, 0, 2], 
        [0, 0, 7, 0, 9, 14, 0, 0, 0], 
        [0, 0, 0, 9, 0, 10, 0, 0, 0], 
        [0, 0, 4, 14, 10, 0, 2, 0, 0], 
        [0, 0, 0, 0, 0, 2, 0, 1, 6], 
        [8, 11, 0, 0, 0, 0, 1, 0, 7], 
        [0, 0, 2, 0, 0, 0, 6, 7, 0]])
print(a)

[[ 0  4  0  0  0  0  0  8  0]
 [ 4  0  8  0  0  0  0 11  0]
 [ 0  8  0  7  0  4  0  0  2]
 [ 0  0  7  0  9 14  0  0  0]
 [ 0  0  0  9  0 10  0  0  0]
 [ 0  0  4 14 10  0  2  0  0]
 [ 0  0  0  0  0  2  0  1  6]
 [ 8 11  0  0  0  0  1  0  7]
 [ 0  0  2  0  0  0  6  7  0]]


ACCESS ELEMENT OF MATRIX

In [18]:
el=a[1]
print(el)
el1=a[1,0]
print(el1)

[ 4  0  8  0  0  0  0 11  0]
4


ENTER ELEMENT IN A MATRIX

In [19]:
a[1,0]=10
print(a)

[[ 0  4  0  0  0  0  0  8  0]
 [10  0  8  0  0  0  0 11  0]
 [ 0  8  0  7  0  4  0  0  2]
 [ 0  0  7  0  9 14  0  0  0]
 [ 0  0  0  9  0 10  0  0  0]
 [ 0  0  4 14 10  0  2  0  0]
 [ 0  0  0  0  0  2  0  1  6]
 [ 8 11  0  0  0  0  1  0  7]
 [ 0  0  2  0  0  0  6  7  0]]


In [20]:
a[1,0]=1
print(a)

[[ 0  4  0  0  0  0  0  8  0]
 [ 1  0  8  0  0  0  0 11  0]
 [ 0  8  0  7  0  4  0  0  2]
 [ 0  0  7  0  9 14  0  0  0]
 [ 0  0  0  9  0 10  0  0  0]
 [ 0  0  4 14 10  0  2  0  0]
 [ 0  0  0  0  0  2  0  1  6]
 [ 8 11  0  0  0  0  1  0  7]
 [ 0  0  2  0  0  0  6  7  0]]


ACCESS COMPLETE ROW OF A MATRIX

In [21]:
row=a[1]
print(row)
row1=a[0]
print(row1)

[ 1  0  8  0  0  0  0 11  0]
[0 4 0 0 0 0 0 8 0]


FETCHING COLUMN OF MATRIX

In [22]:
r=a[:,1]
print("Second column=",r)

Second column= [ 4  0  8  0  0  0  0 11  0]


DJIKSTRA PROGRAM

In [23]:
def minDistance(dist,n,s):  
        min =9999 
        for v in range(n): 
            if dist[v] < min and s[v] == False: 
                min = dist[v] 
                min_index = v 
  
        return min_index 

def djikstra(src,n): 
  
        dist = [99999]*n 
        dist[src] = 0                #initializing src = 0 so that it is picked first
        s= [False]*n
  
        for i in range(n):  
            u = minDistance(dist, n, s)       #picking minimum distance value from src
            s[u] = True                       #marking it true
   
            for w in range(n):                #updating distance value of all adjacent vertices of u
                if a[u][w] > 0 and s[w] == False and dist[w] > dist[u] + a[u][w]: 
                        dist[w] = dist[u] + a[u][w] 
  
        printSolution(dist,n) 
def printSolution( dist,n): 
        print ("Vertex Distance from Source")
        for i in range(n): 
            print(i, "\t", dist[i]) 
djikstra(0,len(a))

Vertex Distance from Source
0 	 0
1 	 4
2 	 12
3 	 19
4 	 21
5 	 11
6 	 9
7 	 8
8 	 14
